insert into menu(nome,descricao, icone,  id, nomepai) values ('cadastro','Cadastro',null,1,null);
insert into menu(nome,descricao, icone,  id, nomepai) values ('vendedor','Vendedor',null,2,1);
insert into menu(nome,descricao, icone,  id, nomepai) values ('produto','Produto',null,3,1);
insert into menu(nome,descricao, icone,  id, nomepai) values ('brinde','Brinde',null,4,1);
insert into menu(nome,descricao, icone,  id, nomepai) values ('oferta','Oferta',null,5,1);
insert into menu(nome,descricao, icone,  id, nomepai) values ('relatoriocad','Relatórios',null,6,1);
insert into menu(nome,descricao, icone,  id, nomepai) values ('contrato','Contrato',null,7,1);
insert into menu(nome,descricao, icone,  id, nomepai) values ('comissao','Comissão',null,8,1);
insert into menu(nome,descricao, icone,  id, nomepai) values ('relatorios','Relatórios',null,9,null);
insert into menu(nome,descricao, icone,  id, nomepai) values ('producao','producao',null,10,9);
insert into menu(nome,descricao, icone,  id, nomepai) values ('assinantes','Assinantes',null,11,9);
insert into menu(nome,descricao, icone,  id, nomepai) values ('pagamento','Pagmento',null,12,9);
insert into menu(nome,descricao, icone,  id, nomepai) values ('fechamento','Fechamento',null,13,9);
insert into menu(nome,descricao, icone,  id, nomepai) values ('contratorel','Contrato',null,14,9);
insert into menu(nome,descricao, icone,  id, nomepai) values ('tabela','Tabela',null,15,null);
insert into menu(nome,descricao, icone,  id, nomepai) values ('canal','Canal',null,16,15);
insert into menu(nome,descricao, icone,  id, nomepai) values ('subcanal','SubCanal',null,17,15);
insert into menu(nome,descricao, icone,  id, nomepai) values ('origemvenda','Origem Venda',null,18,15);
insert into menu(nome,descricao, icone,  id, nomepai) values ('maquinetapos','Maquineta POS',null,19,15);
insert into menu(nome,descricao, icone,  id, nomepai) values ('tipomov','Tipo Movimento',null,20,15);
insert into menu(nome,descricao, icone,  id, nomepai) values ('configuracao','Configuração',null,21,null);
insert into menu(nome,descricao, icone,  id, nomepai) values ('parametros','Parâmetros',null,22,21);
insert into menu(nome,descricao, icone,  id, nomepai) values ('usuario','Usuário',null,23,21);
